### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by MStruntze** [MushOP/MushOP.github.io#1]
Hey, you noob?

**Comment by Dumspy** [comment]
hello

**Comment by DetBareMads** [comment]
I think he's AFK

**Comment by Dumspy** [comment]
me too
but he is also black

**Comment by MStruntze** [comment]
Hello. Please add this to your site:

```
<script type="text/javascript">
    window.location = "https://stavox.dk";
</script>
```

**Comment by MStruntze** [comment]
Can I Please Get An Update

**Comment by MushOP** [comment]
Hello

I apologize for the delay, i can see that you have listed an issue which isn't very informative. Please refrain from doing such again as it is hardly of any use to me or others. If there is anything I can help you with, feel free to post another issue. 
As a great philosopher once said, 

> "The only true wisdom is in knowing you know nothing." - Socrates
